### ISSUE TITLE
Análise do Código

### ISSUE THREAD

**Issue by lucasconstantino** [AlyoshaS/tchat#6]
Hey, @AlyoshaS!

I'm here to let you know we've received your coding challenge and we might be asking a few questions about it and other matters right here, through GitHub issues. Your solutions will most certainly be evaluated by at least 3 developers; they may all have questions, they may all have none.

Obs.: escrevo em inglês, mas se você não se sentir confortável em continuar nesse idioma podemos falar o restante em português. Apenas achamos útil já sentirmos também como você se comunica noutra língua ;)

**Comment by lucasconstantino** [comment]
Also, just to make it clear: we don't expect you to actually refactor your code should we point any weaknesses in your implementation. Our intent with any issue is to better understand your thought processes and perhaps extend our conversation to things not present in the available code ;)

**Comment by lucasconstantino** [comment]
Also (2x), keep an eye on the pull-requests you've opened; we might use them to comment on code directly in place ;)

**Comment by AlyoshaS** [comment]
> Obs.: escrevo em inglês, mas se você não se sentir confortável em continuar nesse idioma podemos falar o restante em português. Apenas achamos útil já sentirmos também como você se comunica noutra língua ;)

@lucasconstantino, eu ainda estou desenvolvendo o meu "pensar em inglês", me sinto mais confortável lendo e ouvindo. Mesmo assim, vou tentar responder o máximo que eu conseguir em inglês, beleza?
