### ISSUE TITLE
[Git] Commit message pattern

### ISSUE THREAD

**Issue by lucasconstantino** [AlyoshaS/tchat#8]
I've noticed your git commits follow some kind of pattern: they started with either _BUG_, _ENH_, or _FIX_, for instance. Could you elaborate on that pattern?

**Comment by AlyoshaS** [comment]
@lucasconstantino, the idea is to create a filter so you can see what kind of branch that pull request comes from. This mainly helps the reviewer. 
A practical example would be:
Assuming the reviewer wants to review the bug's pull requests first: the reviewer would only need to search for the word "bug" in the filter and he/she wouldn't have to look for each of them in the pull request's page.

**Comment by lucasconstantino** [comment]
Oh, now I realized it was used in the pull-request naming as well... I guess the same answer applies to commit messages, though. Thanks for the clarification ;)
